export class Users{
	constructor(
		public email: string,
		public password: string,
		public surnameA: string,
		public surnameB: string,
		public typeOfUser: string,
		public initialToken: string,
		public typeOfOperation: string,
		public nameOfOperation: string,
		public addressU: string,
		public gas: string,
		public hashX: string,
		public status: any,
		public creationDate: string,
		public nameOfUser: string,
		public dp1: any,
		public dp2: any,
		public dp3: any,
		public dp4: any,
		public dp5: any,
		public dp6: any,
		public dp7: any,
		public dp8: any,
		public dp9: any,
		public dp10: any,
		public dp11: any,
		public dp12: any,
		public dp13: any,
		public dp14: any,
		public dp15: any,
		public dp16: any
	){}
}
